# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField()),
                ('rating_description', models.CharField(max_length=256)),
                ('rating_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=32)),
                ('dish_description', models.CharField(max_length=256)),
                ('dish_price', models.IntegerField()),
                ('category', models.CharField(max_length=16)),
                ('availability', models.BooleanField(default=True)),
                ('speciality', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=64)),
                ('restaurant_mobile', models.CharField(max_length=20)),
                ('restaurant_address', models.CharField(blank=True, max_length=512)),
                ('restaurant_pincode', models.IntegerField()),
                ('restaurant_starttime', models.TimeField(null=True)),
                ('restaurant_endtime', models.TimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='foodapp.RestaurantProfileInfo'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='foodapp.RestaurantProfileInfo'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='foodapp.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodapp.RestaurantMenu'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodapp.UserProfileInfo'),
        ),
    ]
