# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20180822_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofileinfo',
            name='restaurant_avgrating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
